{
    "estimationdata"[
        {
            "location":"Jigani",
            "typeofform":"Quotation Estimation Form",
            "type":"Job Work",
            "qtnno":"2023/03/013",
            "status":"Created",
            
            "cusname":"MAGOD LASER MACHINING PVT. LTD.",
            "enquiryref":"test",
            "enquirydate":"02/03/23",
            "contact":"Santhosh",
            "tele":"",


            "taskno":"1",
            "taskname":"Laser Cutting Oxygen / Insp1 / Standard(+/-0.1mm)- 100 Microns",
            "material":"Mild Steel / HR / 10 mm / Sheet MS HR 10",
            "loc":"29.9",
            "pierces":"140",
            "drawings":"3",
            "drawingnested":"3",
            "parts":"3",
            "partsnested":"30",
            "nests":"1",
            "nestssheet":"1",
            "net":"93.64",
            "rect":"143.27",
            "neastdweight":"146.8",
            "cutting":"100",
            "piercerate":"1",
            "setup":"110",
            "sheetloadingrate":"10",
            "materialhandling":"1.5",
            "materialrate":"0",
            "cuttingcharge":"3,130.00",
            "programming":"193.00",
            "setupsheethandling":"110.00",
            "materialhdlgcharge":"220.20",
            "baseratejobwork":"3,653.20",
            "baseratematerial":"0.00",
            "ratemtr":"122.18",
            "ratekg":"39.01",
            "jobwork":"3653.2",
            "materialcharge":"0.00",


            "drawingname":"KBLC05P01523P1_P100",
            "qty":"10",
            "nested":"10",
            "loctable":"0.97",
            "pierce":"5",
            "cf":"0.19030",
            "dwgs":"True",
            "perimeter":"False",
            "open":"False",
            "jwcost":"107.68",
            "mtrlcost":"0.00",
            "total":"1,076.80"

        },
        {
            "taskno":"2",
            "taskname":"Laser Cutting Oxygen / Insp1 / Standard(+/-0.1mm)- 100 Microns",
            "material":"Aluminium / Basic / 0.2 mm / Sheet AL 0.2",
            "loc":"7.5",
            "pierces":"50",
            "drawings":"1",
            "drawingnested":"1",
            "parts":"1",
            "partsnested":"10",
            "nests":"1",
            "nestssheet":"1",
            "net":"0.08",
            "rect":"0.08",
            "neastdweight":"0.1",
            "cutting":"30",
            "piercerate":"2",
            "setup":"210",
            "sheetloadingrate":"10",
            "materialhandling":"2",
            "materialrate":"0",
            "cuttingcharge":"325.00",
            "programming":"81.00",
            "setupsheethandling":"210.00",
            "materialhdlgcharge":"10.00",
            "baseratejobwork":"626.00",
            "baseratematerial":"0.00",
            "ratemtr":"83.47",
            "ratekg":"7,825.00",
            "jobwork":"626",
            "materialcharge":"0.00",


            "drawingname":"KBLS03H01745P1_P100",
            "qty":"10",
            "nested":"10",
            "loctable":"0.75",
            "pierce":"5",
            "cf":"0.13910",
            "dwgs":"True",
            "perimeter":"False",
            "open":"False",
            "jwcost":"62.60",
            "mtrlcost":"0.00",
            "total":"626.00"
        },
        {
            "taskno":"3",
            "taskname":"Laser Cutting Oxygen / Insp1 / Standard(+/-0.1mm)- 100 Microns",
            "material":"Mild Steel / HR / 2 mm / Sheet MS HR 2",
            "loc":"16.2",
            "pierces":"40",
            "drawings":"1",
            "drawingnested":"1",
            "parts":"1",
            "partsnested":"10",
            "nests":"1",
            "nestssheet":"1",
            "net":"11.76",
            "rect":"23.45",
            "neastdweight":"24.07",
            "cutting":"30",
            "piercerate":"2",
            "setup":"60",
            "sheetloadingrate":"10",
            "materialhandling":"1.5",
            "materialrate":"0",
            "cuttingcharge":"566.00",
            "programming":"71.00",
            "setupsheethandling":"60.00",
            "materialhdlgcharge":"36.09",
            "baseratejobwork":"733.08",
            "baseratematerial":"0.00",
            "ratemtr":"45.25",
            "ratekg":"62.34",
            "jobwork":"733.09",
            "materialcharge":"0.00",


            "drawingname":"KBLS12P01431P1_P100",
            "qty":"10",
            "nested":"10",
            "loctable":"1.62",
            "pierce":"4",
            "cf":"0.02270",
            "dwgs":"True",
            "perimeter":"False",
            "open":"False",
            "jwcost":"73.31",
            "mtrlcost":"0.00",
            "total":"733.10"
        },
        {
            "taskno":"4",
            "taskname":"Laser Cutting Oxygen / Insp1 / Standard(+/-0.1mm)- 100 Microns",
            "material":"Mild Steel / HR / 16 mm / Sheet MS HR 16",
            "loc":"24.6",
            "pierces":"50",
            "drawings":"1",
            "drawingnested":"1",
            "parts":"1",
            "partsnested":"10",
            "nests":"1",
            "nestssheet":"1",
            "net":"175.32",
            "rect":"237.16",
            "neastdweight":"297.36",
            "cutting":"160",
            "piercerate":"2",
            "setup":"160",
            "sheetloadingrate":"10",
            "materialhandling":"1.5",
            "materialrate":"0",
            "cuttingcharge":"4,036.00",
            "programming":"81.00",
            "setupsheethandling":"160.00",
            "materialhdlgcharge":"446.04",
            "baseratejobwork":"4,723.04",
            "baseratematerial":"0.00",
            "ratemtr":"191.99",
            "ratekg":"26.94",
            "jobwork":"4723.04",
            "materialcharge":"0.00",


            "drawingname":"KBLS12P01432P1_P100",
            "qty":"10",
            "nested":"10",
            "loctable":"2.46",
            "pierce":"5",
            "cf":"0.02080",
            "dwgs":"True",
            "perimeter":"False",
            "open":"False",
            "jwcost":"472.30",
            "mtrlcost":"0.00",
            "total":"4723.00"
        }

    ],
    
        "fqestimation"[
            {
                "location":"Jigani",
                "typeofform":"Fabrication Quotation Estimation Form",
                "type":"Job Work",
                "qtnno":"2023/03/013",
                "status":"",
                
                "assemblyname":"BICYCLE",
                "costoflabour":"18,000.00",
                "costofmaterial":"19,450.00",
                "totalamount":"37,450.00",
    
                "fabricationtype1":"Labour Cost Details",
                "type1name":"WHEEL ASSEMBLY",
                "type1estimatedcost":"2,500.00",
                "type1quantity":"1",
                "type1lavourcost":"3,000.00",
                "type1total":"3,000.00",
    
                "fabricationtype2":"BOM Cost Details",
                "type2partname":"BRAKES",
                "type2quantity":"1",
                "type2unitcost":"2,500.00",
                "type2total":"15,000.00"    
        },
        {
            "type1name":"WHEEL ASSEMBLY",
            "type1estimatedcost":"2,500.00",
            "type1quantity":"1",
            "type1lavourcost":"3,000.00",
            "type1total":"3,000.00",
    
            "type2partname":"BRAKES",
            "type2quantity":"1",
            "type2unitcost":"2,500.00",
            "type2total":"15,000.00"   
    
    
    
        }
    
       ]
     
}